### ISSUE TITLE
Create M3AAWG HTML styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/m3d-style#1]
M3AAWG uses PDF output but we can also provide an HTML styling for quicker iteration.

Documents are located here: https://www.m3aawg.org/published-documents

**Comment by ronaldtse** [comment]
@pierrefortier any time for this? Thanks!

**Comment by ronaldtse** [comment]
@pierrefortier ping?

**Comment by pierrefortier** [comment]
Sorry about that! Updated.

**Comment by ronaldtse** [comment]
Thank you @pierrefortier !

@opoudjis could you help integrate into https://github.com/riboseinc/asciidoctor-m3d? Thanks.

**Comment by opoudjis** [comment]
Done
